trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'ilifes-acr-docker'  # Azure DevOps Docker registry connection
  imageName: 'ilifes/php-base'
  dockerfilePath: 'Dockerfile.base'
  tag: 'AB#21'
  containerRegistry: 'ilifesregistry.azurecr.io'  # e.g., ilifesregistry.azurecr.io

stages:
- stage: BuildBaseImage
  displayName: 'Build Base Image Stage'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Base Image'
    pool:
      name: 'Default' # Use your self-hosted agent pool name
    steps:

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
